### ISSUE TITLE
NullPointerException when i use pathVars

### ISSUE THREAD

**Issue by kelvinsleonardo** [tkaczmarzyk/specification-arg-resolver#43]
When i use the pathVar it throws the exception below:

```Caused by: java.lang.NullPointerException: null
	at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770) ~[na:na]
	at java.base/java.util.regex.Matcher.reset(Matcher.java:416) ~[na:na]
	at java.base/java.util.regex.Matcher.<init>(Matcher.java:253) ~[na:na]
	at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133) ~[na:na]
	at net.kaczmarzyk.spring.data.jpa.utils.PathVariableResolver.resolveValue(PathVariableResolver.java:40) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.WebRequestProcessingContext.getPathVariableValue(WebRequestProcessingContext.java:62) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.SimpleSpecificationResolver.resolveSpecArgumentsFromPathVariables(SimpleSpecificationResolver.java:141) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.SimpleSpecificationResolver.resolveSpecArguments(SimpleSpecificationResolver.java:128) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.SimpleSpecificationResolver.buildSpecification(SimpleSpecificationResolver.java:54) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.AndSpecificationResolver.buildSpecification(AndSpecificationResolver.java:59) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.AnnotatedSpecInterfaceArgumentResolver.buildSpecification(AnnotatedSpecInterfaceArgumentResolver.java:113) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.AnnotatedSpecInterfaceArgumentResolver.resolveSpecFromInterfaceAnnotations(AnnotatedSpecInterfaceArgumentResolver.java:95) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.AnnotatedSpecInterfaceArgumentResolver.resolveArgument(AnnotatedSpecInterfaceArgumentResolver.java:64) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.SpecificationArgumentResolver.resolveArgument(SpecificationArgumentResolver.java:51) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.JoinSpecificationResolver.resolveArgument(JoinSpecificationResolver.java:64) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.SpecificationArgumentResolver.resolveArgument(SpecificationArgumentResolver.java:49) ~[specification-arg-resolver-2.1.0.jar:na]
	at net.kaczmarzyk.spring.data.jpa.web.SpecificationArgumentResolver.resolveArgument(SpecificationArgumentResolver.java:63) ~[specification-arg-resolver-2.1.0.jar:na]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:126) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:166) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134) ~[spring-web-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	... 97 common frames omitted
```

I've verified the code in the class WebRequestProcessingContext, and the .getPathInfo() method inside the  pathInfo() method returns null. 

Do you have any solution?

**Comment by tkaczmarzyk** [comment]
I merged your PR with the fix. Just released it as 2.1.1. Thank you!
