### ISSUE TITLE
StackOverflowError when attempting to resolve interface with annotated specification

### ISSUE THREAD

**Issue by 1in9ui5t** [tkaczmarzyk/specification-arg-resolver#7]
The only difference I can spot between my and your configuration is that I annotate controllers with @RestController instead of @Controller, but even when I tried it your way...I ran into the same issue.

My interface definition looks like this

`@Spec(path="own", spec=Equal.class)
public interface MyOwnSpec extends Specification<SomeEntity> {
}`

Note however, when I don't use an interface, when I annotate the controller parameter, I don't run into this issue!

`[ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError: null
	at java.lang.Exception.<init>(Exception.java:102) ~[na:1.8.0_45]
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:89) ~[na:1.8.0_45]
	at java.lang.reflect.InvocationTargetException.<init>(InvocationTargetException.java:72) ~[na:1.8.0_45]
	at $java.lang.Object$$FastClassByCGLIB$$3f697993.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at net.kaczmarzyk.spring.data.jpa.web.AnnotatedSpecInterfaceArgumentResolver$1.intercept(AnnotatedSpecInterfaceArgumentResolver.java:140) ~[specification-arg-resolver-0.6.0.jar:na]
	at com.averyjules.backend.web.rest.diamonds.dto.filtering.MyOwnSpec$$EnhancerByCGLIB$$4a09433c.toString(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at $java.lang.Object$$FastClassByCGLIB$$3f697993.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at net.kaczmarzyk.spring.data.jpa.web.AnnotatedSpecInterfaceArgumentResolver$1.intercept(AnnotatedSpecInterfaceArgumentResolver.java:140) ~[specification-arg-resolver-0.6.0.jar:na]
	at com.averyjules.backend.web.rest.diamonds.dto.filtering.MyOwnSpec$$EnhancerByCGLIB$$4a09433c.toString(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at $java.lang.Object$$FastClassByCGLIB$$3f697993.invoke(<generated>) ~[spring-core-4.1.6.RELEASE.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-4.1.6.RELEASE.jar:4.1.6.RELEASE]`

**Comment by tkaczmarzyk** [comment]
hmm, I can't reproduce it :(
1. Which version of Spring and Spring Data do you use?
2. Do you use Spring Boot? If so, then which version? If not, then which version of Tomcat do you use?
3. Please paste your entity (at least the relevant fragment)

**Comment by tkaczmarzyk** [comment]
Hi, I managed to reproduce. It should work fine in v0.8.0
