### ISSUE TITLE
Filter on JoinFetch'ed table

### ISSUE THREAD

**Issue by andreyBelov** [tkaczmarzyk/specification-arg-resolver#97]
Hi, thanks for useful project!
I have a problem very similar to this closed issue https://github.com/tkaczmarzyk/specification-arg-resolver/issues/14

Spec:
```java
@JoinFetch(paths = {"divisions"})
@And({
        @Spec(path = "podrId", spec = Null.class, constVal = "true"),
        @Spec(path = "divisions.name", params = "searchStr", spec = LikeIgnoreCase.class)
})
public interface DepartmentWithDivisionsSpec extends Specification<FsPodrEntity> {}
```
Entity:
```java
@Entity
@Table(name = "FS_PODR", schema = "GKUOP")
@Getter
@Setter
@ToString
public class FsPodrEntity {

    @Id
    private Long id;

    @Column(name = "NAME", nullable = false)
    private String name;

    @Column(name = "PODR_ID")
    private String podrId;

    @OneToMany(cascade = {CascadeType.ALL})
    @JoinColumn(name = "PODR_ID")
    @ToString.Exclude
    private List<FsPodrEntity> divisions;

}
```
I get this error:
```
java.lang.IllegalStateException: Illegal attempt to dereference path source [null.divisions] of basic type
	at org.hibernate.query.criteria.internal.path.AbstractPathImpl.illegalDereference(AbstractPathImpl.java:82) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at org.hibernate.query.criteria.internal.path.AbstractPathImpl.get(AbstractPathImpl.java:174) ~[hibernate-core-5.4.18.Final.jar:5.4.18.Final]
	at net.kaczmarzyk.spring.data.jpa.domain.PathSpecification.path(PathSpecification.java:53) ~[specification-arg-resolver-2.6.1.jar:na]
```
Could the problem be that my entity is hierarchical (i.e. children and parents in the same table) ?
I use last version:
```xml
        <dependency>
            <groupId>net.kaczmarzyk</groupId>
            <artifactId>specification-arg-resolver</artifactId>
            <version>2.6.1</version>
        </dependency>
```
If I don't have request parameter "searchStr" all it's ok and sql query looks like this:
```sql
select distinct fspodrenti0_.id      as id1_2_0_,
                divisions1_.id       as id1_2_1_,
                fspodrenti0_.name    as name2_2_0_,
                fspodrenti0_.podr_id as podr_id3_2_0_,
                divisions1_.name     as name2_2_1_,
                divisions1_.podr_id  as podr_id3_2_1_,
                divisions1_.podr_id  as podr_id3_2_0__,
                divisions1_.id       as id1_2_0__
from gkuop.fs_podr fspodrenti0_
         left outer join gkuop.fs_podr divisions1_ on fspodrenti0_.id = divisions1_.podr_id
where fspodrenti0_.podr_id is null
```

**Comment by jradlica** [comment]
@andreyBelov The need to use two joins in this case (@Join & @JoinFetch) is due to the current library limitations. This should be improved in the next release (in September).

**Comment by tkaczmarzyk** [comment]
Hi @andreyBelov  . Sorry for the huge delay. For whatever it's worth: v2.8.0 was just released and thanks to @jradlica great contribution, the issue should be resolved now.
